#remote_theme: "gaalcaras/academic"
#remote_theme: "reproio/reproio.github.io"
plugins: ["jekyll-include-cache"]
email: "rsbowen@gmail.com"
title: "Richard Strong Bowen"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
