plugins: ["jekyll-include-cache"]
email: "rsbowen@gmail.com"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: "Richard Strong Bowen"
minimal_mistakes_skin : "contrast"
author:
  name: "Richard Strong Bowen, PhD"
  bio: "CV researcher"
  avatar: "headshot.jpg"
  location: "New York City"
  links:
    - label: "Email"
      url: "mailto:rsbowen@gmail.com"
    - label: "DBLP"
      url: "https://dblp.org/pid/37/5252.html"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=L38WAT4AAAAJ&hl=en&oi=sra"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/richardstrongbowen/"
atom_feed:
  hide: true
